# Generated by Django 4.2.4 on 2023-08-07 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата оплаты'),
        ),
    ]
