# Generated by Django 4.2.4 on 2023-08-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_payment_date_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_amount',
            new_name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='course.course', verbose_name='оплаченный курс'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='course.lesson', verbose_name='оплаченный урок'),
        ),
    ]
