# Generated by Django 4.2.4 on 2023-08-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_subscription_is_subscribe_alter_subscription_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='start', max_length=25, null=True, verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_url',
            field=models.TextField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='course.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='course.course', verbose_name='подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
