# Generated by Django 4.2.4 on 2023-08-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_price_lesson_price_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
    ]
