# Generated by Django 4.2.4 on 2023-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_course_price_remove_lesson_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='id платежа stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='open', max_length=10, verbose_name='статус платежа'),
        ),
    ]
